export const tabs = [
    'Gold TWW',
    'D4 Gold',
    'Gold WoW Hardcore',
    'POE Currencies',
    'TESO Gold',
    'LA Gold',
    'Gold Classic Season of Discovery',
    'Gold Classic Era',
    'Last Epoch Gold',
    'NW Coins',
    'Cataclysm Gold',
    'Tarisland Gold',
];

export const goldCards = [
    {
        id: 1,
        name: 'Aegwynn Gold',
        deliveryTime: '10 min delivery time',
        inStock: 15002584,
        count: 100,
        price: 4.38,
    },
    {
        id: 2,
        name: 'Aegwynn Gold',
        deliveryTime: '10 min delivery time',
        inStock: 15002584,
        count: 10500,
        price: 4.38,
    },
    {
        id: 3,
        name: 'Aegwynn Gold',
        deliveryTime: '10 min delivery time',
        inStock: 15002584,
        count: 5300,
        price: 4.38,
    },
    {
        id: 4,
        name: 'Aegwynn Gold',
        deliveryTime: '10 min delivery time',
        inStock: 15002584,
        count: 45700,
        price: 4.38,
    },
    {
        id: 5,
        name: 'Aegwynn Gold',
        deliveryTime: '10 min delivery time',
        inStock: 15002584,
        count: 20600,
        price: 4.38,
    },
    {
        id: 6,
        name: 'Aegwynn Gold',
        deliveryTime: '10 min delivery time',
        inStock: 15002584,
        count: 14600,
        price: 4.38,
    },
    {
        id: 7,
        name: 'Aegwynn Gold',
        deliveryTime: '10 min delivery time',
        inStock: 15002584,
        count: 18700,
        price: 4.38,
    },
    {
        id: 8,
        name: 'Aegwynn Gold',
        deliveryTime: '10 min delivery time',
        inStock: 15002584,
        count: 0,
        price: 4.38,
    },
    {
        id: 9,
        name: 'Aegwynn Gold',
        deliveryTime: '10 min delivery time',
        inStock: 15002584,
        count: 2345600,
        price: 4.38,
    },
];


